# Generated by Django 4.0.6 on 2022-09-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on the way', 'on the way'), ('completed', 'completed'), ('not handled', 'not handled')], default='not handled', max_length=200),
        ),
    ]
