# Generated by Django 4.0.6 on 2022-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_style_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('styles', models.ManyToManyField(to='shop.style')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='style_groups',
            field=models.ManyToManyField(to='shop.stylegroup'),
        ),
    ]
