# Generated by Django 4.0.6 on 2022-07-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_item_images_remove_item_style_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
        migrations.AlterField(
            model_name='style',
            name='style_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.stylegroup'),
        ),
        migrations.AlterField(
            model_name='stylegroup',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.item'),
        ),
    ]
