# Generated by Django 4.0.6 on 2022-08-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderitem_quantity_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemstylegroup',
            name='selected_style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.style'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not handled', 'not handled'), ('completed', 'completed'), ('on the way', 'on the way')], default='not handled', max_length=200),
        ),
    ]
