# Generated by Django 4.0.6 on 2022-07-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_image_item_alter_style_style_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
