# Generated by Django 4.0.6 on 2022-07-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_item_price_alter_style_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='keywords',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
