# Generated by Django 4.0.6 on 2022-07-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_item_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='keywords',
            field=models.CharField(blank=True, default='All', max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='categories',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
