# Generated by Django 4.0.6 on 2022-08-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_image_categories_item_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='old_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
