# Generated by Django 4.0.6 on 2022-08-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_navigationdashboard_item_old_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationDashboard',
        ),
    ]
