# Generated by Django 4.0.6 on 2022-08-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='title',
        ),
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(default='logos/logo.png', upload_to='seller_logos'),
        ),
        migrations.AddField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
