# Generated by Django 4.0.6 on 2022-08-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_seller_title_seller_logo_seller_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.seller'),
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.seller'),
        ),
    ]
