# Generated by Django 4.0.6 on 2022-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_category_seller_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='etsy_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
