# Generated by Django 4.0.6 on 2022-08-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_seller_etsy_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='shop.category'),
        ),
    ]
