# Generated by Django 4.0.6 on 2022-08-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_item_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
