# Generated by Django 4.0.6 on 2022-08-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_item_description_item_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
