# Generated by Django 4.0.6 on 2022-08-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_item_description_alter_item_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.item')),
            ],
        ),
        migrations.CreateModel(
            name='ParentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemStyleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem')),
                ('style_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.stylegroup')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_style_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderitemstylegroup')),
                ('style', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.style')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on the way', 'on the way'), ('not handled', 'not handled'), ('completed', 'completed')], max_length=200)),
                ('ParentOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.parentorder')),
            ],
        ),
    ]
