# Generated by Django 4.0.6 on 2022-08-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_orderitem_parentorder_orderitemstylegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentorder',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on the way', 'on the way'), ('completed', 'completed'), ('not handled', 'not handled')], max_length=200),
        ),
    ]
