# Generated by Django 4.0.6 on 2022-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_parentorder_message_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='delivery_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not handled', 'not handled'), ('on the way', 'on the way'), ('completed', 'completed')], default='not handled', max_length=200),
        ),
    ]
