# Generated by Django 4.0.6 on 2022-08-28 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_orderitem_order_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parentorder',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='parentorder',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('on the way', 'on the way'), ('completed', 'completed'), ('not handled', 'not handled')], default='not handled', max_length=200),
        ),
    ]
