# Generated by Django 4.0.6 on 2022-08-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_order_seller_order_subtotal_order_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not handled', 'not handled'), ('completed', 'completed'), ('on the way', 'on the way')], default='not handled', max_length=200),
        ),
    ]
