# Generated by Django 4.0.6 on 2022-08-28 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ParentOrder',
            new_name='parentOrder',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Seller',
            new_name='seller',
        ),
    ]
