# Generated by Django 4.0.6 on 2022-08-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_rename_parentorder_order_parent_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentorder',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not handled', 'not handled'), ('on the way', 'on the way'), ('completed', 'completed')], default='not handled', max_length=200),
        ),
    ]
